
services:
#     nginx-proxy:
#         # http://blog.florianlopes.io/host-multiple-websites-on-single-host-docker
#         image: jwilder/nginx-proxy
#         container_name: nginx-proxy
#         ports:
#           - "80:80"
#           - "443:443"
#         volumes:
#           - /var/run/docker.sock:/tmp/docker.sock:ro
#         restart: always
    mysql_db:
        image: mysql:latest
        ports: 
          -  3307:3307
        environment:
          -  DB_DATABASE=cp101_db
          -  DB_PASSWORD=123password
          -  DB_USERNAME=cp101_user
          -  MYSQL_ROOT_PASSWORD=secret
        volumes:
          - mysql_db_data:/var/lib/mysql
            
    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
          -  mysql_db
        environment:
          PMA_HOST: mysql_db
          PMA_USER: root
          PMA_PASSWORD: secret
        ports:
          - 8081:8081
          
    sveltekit:
#       https://stackoverflow.com/questions/65312857/building-a-docker-image-from-a-private-github-repository-with-docker-compose
        build: ./
        restart: always
        depends_on:
          -  mysql_db
               
#         build: https://${GIT_TOKEN}@github.com/zipzit/cellphone101/blob/main/Dockerfile
#         build: https://raw.githubusercontent.com/zipzit/cellphone101/main/Dockerfile?token=ABBVNTWSQ7GKLADCMXYDQL3BQNZRI
        environment:
           - NODE_ENV=develop
#            - REACT_APP_API_BASE_URL=http://192.168.1.15:8080/api
#            - REACT_APP_IMAGE_URL=http://192.168.1.15:8080
#            - REACT_APP_PUBLIC_URL=http://192.168.1.15:8080
        ports:
            - 3000:3000
            - 24678:24678
        container_name: "sveltekit_server"
        volumes:
            - sveltekit:/usr/src/app
            - ./sveltekit2:/app
            - '/app/node_modules'
        
volumes:
    sveltekit: {}
    mysql_db_data: {}
#     test_node_modules: {}

